format = """
[█](#271224)\
$username @[](bg:#291E37 fg:#271224)\
$hostname[](bg:#4E4A89 fg:#291E37)\
$directory[](bg:#493961 fg:#4E4A89)\
$git_branch$git_status[](bg:#271224 fg:#493961)\
$nodejs$python$rust$golang$php[](bg:#271224 fg:#271224)\
$time[](#271224)\
\n\
[└──](#271224 bold #6391D8) $character
"""

[character]
success_symbol = "[❯](bold #6391D8)"
error_symbol   = "[❯](bold #f7768e)"   # keep red for errors
vicmd_symbol   = "[❮](bold #73daca)"

[username]
show_always = true
style_user = "bg:#271224 bold #6391D8"
style_root = "bg:#271224 bold #f7768e"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bg:#291E37 bold #73daca"
format = "[$hostname]($style)"

[directory]
style = "bg:#4E4A89 bold #6391D8"
read_only = " "
read_only_style = "bold #f7768e"
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style)"

[git_branch]
symbol = " "
style = "bg:#493961 bold #6391D8"
format = "[$symbol$branch]($style)"

[git_status]
style = "bg:#3D355F bold #e0af68"
format = '([$all_status$ahead_behind]($style))'

[dotnet]
symbol = " "
style = "bg:#271224 bold #73daca"
format = "[$symbol$version]($style)"

[nodejs]
symbol = " "
style = "bg:#271224 bold #e0af68"
format = "[$symbol$version]($style)"

[python]
symbol = " "
style = "bg:#271224 bold #f7768e"
format = "[$symbol$version]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#271224 bold #73daca"
format = "[ $time]($style)"

